import Head from 'next/head'
import Main_Com from '../components/main/main'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Color Match</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main_Com />
    </div>
  )
}
